In [1]:
import torch

print(torch.__version__)

2.0.1+cu118


In [2]:
# 测试GPU是否可用.
print(torch.cuda.is_available())
print(torch.cuda.get_device_name())

True
NVIDIA GeForce GTX 1650


#### 创建张量

In [3]:
import torch
import numpy as np

np.set_printoptions(precision=3)
a = [1, 2, 3]
b = np.array([4, 5, 6], dtype=np.int32)

t_a = torch.tensor(a)
t_b = torch.from_numpy(b)

print(type(a), type(b))
print(type(t_a), type(t_b))
print(t_a, t_b)

<class 'list'> <class 'numpy.ndarray'>
<class 'torch.Tensor'> <class 'torch.Tensor'>
tensor([1, 2, 3]) tensor([4, 5, 6], dtype=torch.int32)


In [4]:
# 查看b和t_b的形状.
print(b.shape, t_b.shape)

(3,) torch.Size([3])


In [5]:
t_ones = torch.ones(2, 3)
t_ones.shape

torch.Size([2, 3])

In [6]:
print(t_ones)

tensor([[1., 1., 1.],
        [1., 1., 1.]])


In [7]:
# 创建一个由随机数组成的张量.
rand_tensor = torch.rand(2, 3)
print(rand_tensor)

tensor([[0.9097, 0.3582, 0.6472],
        [0.0911, 0.1728, 0.4163]])


In [8]:
print(rand_tensor.mean(), rand_tensor.std())

tensor(0.4325) tensor(0.3045)


#### 更改张量形状与数据类型

In [9]:
# torch.to方法可以更改张量数据类型.
t_a_new = t_a.to(torch.int64)
print(t_a.dtype, t_a_new.dtype)

torch.int64 torch.int64


In [10]:
t_b_new = t_b.to(torch.int64)
print(t_b.dtype, t_b_new.dtype)

torch.int32 torch.int64


In [11]:
# 张量形状操作.
"""
 * (Tensor input, int dim0, int dim1)
 * (Tensor input, name dim0, name dim1)
"""
t = torch.rand(3, 5)
t_tr = torch.transpose(t)
t_tr

TypeError: transpose() received an invalid combination of arguments - got (Tensor), but expected one of:
 * (Tensor input, int dim0, int dim1)
 * (Tensor input, name dim0, name dim1)


In [13]:
t = torch.rand(3, 5)
print(t)
# 0 和 1 表示要交换的维度；
# 这里将行和列进行交换，得到一个形状为 (5, 3) 的新张量.
t_tr = torch.transpose(t, 0, 1)
t_tr

tensor([[0.9447, 0.6829, 0.8239, 0.5239, 0.9629],
        [0.6176, 0.9883, 0.3022, 0.0527, 0.9887],
        [0.6196, 0.7804, 0.4602, 0.8941, 0.9115]])


tensor([[0.9447, 0.6176, 0.6196],
        [0.6829, 0.9883, 0.7804],
        [0.8239, 0.3022, 0.4602],
        [0.5239, 0.0527, 0.8941],
        [0.9629, 0.9887, 0.9115]])

In [14]:
print(t.shape, '---->', t_tr.shape)

torch.Size([3, 5]) ----> torch.Size([5, 3])


In [15]:
# reshape一个张量.
t = torch.zeros(30)
print(t.shape)

t_reshape = t.reshape(5, 6)
print(t_reshape.shape)

torch.Size([30])
torch.Size([5, 6])


In [16]:
print(t_reshape.size)

<built-in method size of Tensor object at 0x000001D01CFF34F0>


In [17]:
print(t_reshape.size())

torch.Size([5, 6])


In [18]:
# 移除无用的维度.
t = torch.zeros(1, 2, 1, 4, 1)
print(t.shape)

t_sqz = torch.squeeze(t, 2)
print(t_sqz.shape)

torch.Size([1, 2, 1, 4, 1])
torch.Size([1, 2, 4, 1])


#### 对张量执行数学运算